# Generated by Django 3.0.8 on 2021-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210502_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_choice',
            name='regular',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza_choice',
            name='square',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
