# Generated by Django 3.0.8 on 2021-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210502_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='regular',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='square',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_pizza',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
