# Generated by Django 3.0.8 on 2021-05-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pizza_choice_regular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_pizza',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='pizza_size',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='regular',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_your_pizza_regular',
            field=models.BooleanField(default=False, verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='square',
            field=models.BooleanField(default=False, verbose_name='Regular'),
        ),
    ]
