# Generated by Django 3.0.8 on 2021-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210502_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_pizza',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='pizza_size',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
