# Generated by Django 3.0.8 on 2021-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210502_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_pizza',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_your_pizza_regular',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='square',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='capsicum',
            field=models.BooleanField(default=False, verbose_name='Capsium_toppings'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='cheese',
            field=models.BooleanField(default=False, verbose_name='Cheese_toppings'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='corn',
            field=models.BooleanField(default=False, verbose_name='Corn_Toppings'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='jalapeno',
            field=models.BooleanField(default=False, verbose_name='Jalapeno_toppings'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='onion',
            field=models.BooleanField(default=False, verbose_name='Onion_toppings'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='regular',
            field=models.BooleanField(default=False, verbose_name='Regular_pizza'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='tomoato',
            field=models.BooleanField(default=False, verbose_name='Tomato_Toppings'),
        ),
    ]
