# Generated by Django 3.0.8 on 2021-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210502_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_pizza',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
