# Generated by Django 3.0.8 on 2021-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pizza_choice_choose_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_choice',
            name='square',
            field=models.BooleanField(default=False, verbose_name='Square_pizza'),
        ),
    ]
