# Generated by Django 3.0.8 on 2021-05-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pizza_choice_square'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza_choice',
            old_name='tomoato',
            new_name='tomato',
        ),
    ]
