# Generated by Django 3.0.8 on 2021-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210502_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_choice',
            name='toppings',
            field=models.CharField(max_length=150, verbose_name='Add another toopings'),
        ),
    ]
