# Generated by Django 3.0.8 on 2021-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210502_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_choice',
            name='pizza_size_avalible',
            field=models.CharField(default='small', max_length=100),
        ),
    ]
