# Generated by Django 3.0.8 on 2021-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pizza_choice_pizza_size_avalible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='pizza_size_avalible',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='pizza_size_avalibles',
            field=models.CharField(choices=[('small', 'Small'), ('regular', 'regular'), ('large', 'Large')], default='small', max_length=100),
        ),
    ]
