# Generated by Django 3.0.8 on 2021-05-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210502_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_pizza',
        ),
    ]
