# Generated by Django 3.0.8 on 2021-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_pizza_choice_choose_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='pizza_size_avalibles',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_shape_pizzas',
            field=models.CharField(choices=[('regular', 'Regular'), ('square', 'square')], default='small', max_length=100),
        ),
    ]
