# Generated by Django 3.0.8 on 2021-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210503_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='regular',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='square',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='large',
            field=models.BooleanField(default=False, verbose_name='Large_pizza'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='medium',
            field=models.BooleanField(default=False, verbose_name='Medium_pizza'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='small',
            field=models.BooleanField(default=False, verbose_name='small_pizza'),
        ),
    ]
