# Generated by Django 3.0.8 on 2021-05-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210503_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_choice',
            name='pizza_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza_choice',
            name='small',
            field=models.BooleanField(default=False, verbose_name='small, _pizza'),
        ),
        migrations.AlterField(
            model_name='pizza_choice',
            name='toppings',
            field=models.CharField(blank=True, max_length=150, verbose_name='Add another toopings'),
        ),
    ]
