# Generated by Django 3.0.8 on 2021-05-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210503_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='name',
        ),
    ]
