# Generated by Django 3.0.5 on 2021-05-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_pizza_choice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_choice',
            name='name',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
