# Generated by Django 3.0.5 on 2021-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_pizza_choice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_shape_pizzas',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_pizzas_regular',
            field=models.BooleanField(default=False, verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_pizzas_square',
            field=models.BooleanField(default=False, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='pizza_choice',
            name='small',
            field=models.BooleanField(default=False, verbose_name='small_pizza'),
        ),
    ]
