# Generated by Django 3.0.5 on 2021-06-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210620_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_pizzas_regular',
        ),
        migrations.RemoveField(
            model_name='pizza_choice',
            name='choose_pizzas_square',
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='choose_shape_pizzas',
            field=models.CharField(choices=[('regular', 'Regular'), ('square', 'square')], default='small', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza_choice',
            name='name',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='pizza_choice',
            name='small',
            field=models.BooleanField(default=False, verbose_name='small, _pizza'),
        ),
    ]
